jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: {{env_var('POSTGRES_ACCOUNT'['POSTGRES_USER'])}}
      password: "{{env_var('POSTGRES_ACCOUNT'['POSTGRES_PASSWORD'])}}"
      port: 5432
      dbname: postgres
      schema: public
      threads: 4
  
