jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{env_var('AIRFLOW_POSTGRES_USE')}}"
      password: "{{env_var('AIRFLOW_POSTGRES_PASSWOR')}}"
      port: 5432
      dbname: postgres
      schema: mart
      threads: 6
  
