jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: "{{env_var('AIRFLOW_POSTGRES_PASSWORD')}}"
      port: 5432
      dbname: postgres
      threads: 6
  
