jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{var('POSTGRES_USER')}}"
      password: "{{var('POSTGRES_PASSWORD')}}"
      port: 5432
      dbname: postgres
      schema: public
      threads: 4
  
